### PR TITLE
Query support

### PR DESCRIPTION
**Pull request by tmoerman**
Adds lightweight support for querying a workflow.

### CODE REVIEW

**Comment by ghaskins** [comment]
Hi @tmoerman.  Code looks good, ty.

Could I ask one favor: Add a new query.md to ./doc?  That way, it will show up prominently on our doc site: https://cljdoc.org/d/io.github.manetu/temporal-sdk/0.12.3/doc/readme

You can probably use this as a template/head-start (it is what I did for most of the other sections...shout-out to the java documentation folks!)
https://docs.temporal.io/dev-guide/java/features#queries

**Comment by ghaskins** [comment]
I think this code looks good so I'm going to merge it and cut a release.  I'd still be interested in documentation if you are inclined to contribute this.  Thank you for the contribution!

**Review by ghaskins — APPROVED** [review]
Thank you!

**Comment by tmoerman** [comment]
Added some docs in https://github.com/manetu/temporal-clojure-sdk/pull/38

**Pull request merged**
