### PR TITLE
Add clj-kondo exports

### PR DESCRIPTION
**Pull request by kpassapk**
Great library!

This configuration helps clj-kondo understand the `defworkflow` and `defactivity` macros.

Let me know if you have better ideas on how to organize the resources path. I thought `dev/user.clj`, `dev/utils.clj` and  `dev/resources` kinda made sense.

### CODE REVIEW

**Comment by ghaskins** [comment]
Hi,

Thanks for the patch, and sorry for the delay in responding.  I somehow missed the notification from GH.

I'm curious about why you moved the dev-resources files. I generally use them in all of my projects since they are in the path by default. Does this cause a problem with clj-kondo?

**Comment by kpassapk** [comment]
Ah, I didn't know it was a special directory name. I can see now that Leiningen adds it to the resource paths automatically. I'm six months into Clojure, and have only been using tools.deps until now. 

It doesn't cause a problem with clj-kondo. I have seen other tools.deps projects using `dev` and I thought `dev/resources` sounded better than `dev-resources/resources`. 

How about this?

```
dev-resources/resources/clj-kondo/clj-kondo.exports/io.github.manetu/temporal-sdk/config.edn
```

**Comment by ghaskins** [comment]
That seems reasonable to me.

**Comment by kpassapk** [comment]
I found a list of projects which have added similar exports [here](https://github.com/clj-kondo/clj-kondo/issues/1383). The done thing seems to be to use the resources directory, even in projects with no other resource. (See [helix](https://github.com/lilactown/helix/tree/master)). 

I went ahead and replicated the style used here, leaving the dev-resources directory alone. I can confirm it works on a couple of projects. LMK.

**Comment by ghaskins** [comment]
Code looks fine.  I'm not sure what's up with CI.  I might have to tweak something there.

**Review by ghaskins — APPROVED** [review]

**Comment by ghaskins** [comment]
Note that I submitted an MR recently, and it successfully ran through CI.  I am not sure why yours isn't

**Comment by kpassapk** [comment]
I think this is due to circleci configuration on my side. I created #62 with the same code and it passes. Closing this one.

**Pull request closed without merging**
